services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2019
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=ApiTest2024
      - ACCEPT_EULA=Y
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata: